#!/bin/sh

export AXIOM="${FRICAS_PREFIX}/lib/fricas/target/x86_64-unknown-linux"
AXIOMSYS="${AXIOM}/bin/AXIOMsys"

axiom_read() {
  "${AXIOMSYS}" << EOF
)lisp (declaim (sb-ext:muffle-conditions cl:warning))
)set break quit
)read $1
EOF
}

axiom_compile() {
  "${AXIOMSYS}" << EOF
)lisp (declaim (sb-ext:muffle-conditions cl:warning))
)set break quit
)read load.input
)read testinit.input
)compile $1
EOF
}

axiom_call() {
  "${AXIOMSYS}" << EOF
)lisp (declaim (sb-ext:muffle-conditions cl:warning))
)set break quit
)read load.input
$1
EOF
}

action=$1
shift

[ -z "$action" ] && exit 1

case $action in
  --compile)
    axiom_compile $@;;
  --call)
    axiom_call $@;;
  --read)
    axiom_read $@;;
  *)
    exit 1;;
esac
